add support for LOCAL backup/restore
The `iotstack_backup` and `iotstack_restore` methods have assumed one
of SCP, RSYNC or RCLONE has been configured prior to the run, such that
the backup can save the backup files off the local host, and the restore
can fetch the previously-saved backup files across the network.

This change adds support for a LOCAL method which only saves backup
files in the local `~/IOTstack/backups` directory; and only searches
that directory on restore.

Although it is not particularly safe to keep both the working versions
(those in `~/IOTstack/volumes`) and backups on the same machine, the
LOCAL method can be useful for someone who wants to use IOTstackBackup
as part of a rebuild process - just get a local backup on the existing
machine, copy the files using some sensible method, move the files into
place on the rebuilt machine, run the restore.

And then, hopefully, think about configuring IOTstackBackup properly...

Signed-off-by: Phill Kelley <34226495+Paraphraser@users.noreply.github.com>

diff --git a/scripts/iotstack_restore b/scripts/iotstack_restore
--- a/scripts/iotstack_restore
+++ b/scripts/iotstack_restore
@@ -9,6 +9,9 @@ SCRIPT=$(basename "$0")
 # assumptions that can be overridden
 IOTSTACK=${IOTSTACK:-"$HOME/IOTstack"}
 
+# backups are generally stored here
+BACKUPSDIR="$IOTSTACK/backups"
+
 # the project name is the all-lower-case form of the folder name
 PROJECT=$(basename ${IOTSTACK,,})
 
@@ -83,8 +86,8 @@ else
 fi
 
 # apply defaults if not set from configuration file
-CLOUD_METHOD=${CLOUD_METHOD:-"SCP"}
-CLOUD_PREFIX=${CLOUD_PREFIX:-"myuser@myhost.mydomain.com:/path/to/backup/directory/on/myhost"}
+CLOUD_METHOD=${CLOUD_METHOD:-"LOCAL"}
+CLOUD_PREFIX=${CLOUD_PREFIX:-"$HOME/IOTstack/backups"}
 
 # form the cloud path
 CLOUD_PATH="$CLOUD_PREFIX/$BY_HOST_DIR"
@@ -120,6 +123,15 @@ echo "Attempting to fetch backup images for $RUNTAG"
 
 case "$CLOUD_METHOD" in
 
+  "LOCAL" )
+    if [ -d "$BACKUPSDIR" ] ; then
+       cp -v "$BACKUPSDIR/$RUNTAG".* "$RESTOREDIR"
+    else
+       echo "Error: $BACKUPSDIR does not exist"
+       exit 1
+    fi
+    ;;
+
   "RCLONE" )
     rclone copy -v $CLOUD_OPTIONS --include "$RUNTAG.*" "$CLOUD_PATH" "$RESTOREDIR"
     ;;
@@ -130,7 +142,7 @@ case "$CLOUD_METHOD" in
 
   * )
     echo "Warning: $CLOUD_METHOD backup method is not supported"
-    echo "Warning: The only backup files are the ones in $BACKUPSDIR"
+    exit 1
     ;;
 
 esac
